services:
  bank_documents_to_csv:
    image: ghcr.io/rpadafo/bank_documents_to_csv:latest
    container_name: bankdocumentstocsv
    restart: unless-stopped
    environment:
      - RETENTION_HOUR=12
      #optional >>
      - PREFIX_BANKINTER=BANK
      - PREFIX_CAIXA=CAIX
      - PREFIX_SABADELL=SABA
      - PREFIX_SANTANDER=SANT
    deploy:
        resources:
            limits:
                cpus: '1'
                memory: 100M
    volumes:
      # Two folders required, excel and CSV >>
      - ./excel:/excel
      - ./csv:/csv