name: Build and Publish Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile # Asegúrate de poner conf/Dockerfile si lo moviste ahí
          push: true
          # Aquí creamos las dos etiquetas a la vez:
          tags: |
            ghcr.io/${{ github.actor }}/bank_documents_to_csv:latest
            ghcr.io/${{ github.actor }}/bank_documents_to_csv:v26.0.${{ github.run_number }}